name: mamba nightly tests

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  conda_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: mamba
      - name: create mamba build environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: build_env
          environment-file: mamba/mamba/environment-dev.yml
          channels: conda-forge,conda-canary/label/dev
          channel-priority: flexible
          extra-specs: |
            python=3.10
            conda =*+*
      # Build Mamba
      - uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}
          restore-keys: |
            libmamba_static-${{ matrix.os }}

      - name: install libmambapy
        run: |
          cd mamba
          pip install -e ./libmambapy/ --no-deps
      - name: build cache statistics
        run: sccache --show-stats
      - name: install mamba
        run: |
          cd mamba
          pip install ./mamba --no-deps
      # Test Mamba with Conda nightly
      - name: run mamba tests suite
        run: |
          cd mamba
          pytest -v --capture=tee-sys mamba/tests
      - name: run mamba create/update tests
        run: |
          cd mamba
          mamba create -n test_env xtensor -c conda-forge -y
          mamba env create -f mamba/tests/test_env.yml
          mamba env update -f mamba/tests/update_env.yml

    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Conda environment from environment.yml
          uses: mamba-org/provision-with-micromamba@main
        # Linux and macOS
        - name: Run Python
          shell: bash -l {0}
          run: |
            python run_simulation.py -h
