name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd tests & docker build . --progress=plain --no-cache --tag simple_build_and_run
    - name: run the functional and generous stdp file
      run: docker run simple_build_and_run
